# Generated by Django 3.2.3 on 2021-06-02 11:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jet_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jet_name', models.CharField(max_length=200)),
                ('jet_type', models.CharField(max_length=200)),
                ('jet_capacity', models.CharField(max_length=200)),
                ('active', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ticket', models.CharField(max_length=200)),
                ('payment_date', models.DateTimeField(default=datetime.datetime.now)),
                ('payment_amout', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=200)),
                ('booking_satutus', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reservation', models.DateTimeField()),
                ('flight_no', models.CharField(max_length=200)),
                ('journey_date', models.DateTimeField()),
                ('booking_ticket', models.CharField(max_length=200)),
                ('booking_status', models.BooleanField(default=False)),
                ('class_level', models.CharField(max_length=200)),
                ('priority_checkin', models.CharField(max_length=200)),
                ('Payment_details_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='page.payment_details')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ticket', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('meal_choice', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=200)),
                ('to_city', models.CharField(max_length=200)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField(blank=True)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('price_economy', models.IntegerField()),
                ('price_business', models.IntegerField()),
                ('flight_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.jet_detail')),
            ],
        ),
    ]
