# Generated by Django 3.2.3 on 2021-06-02 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_details',
            name='flight_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='page.jet_detail'),
        ),
    ]
