# Generated by Django 3.2.3 on 2021-06-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_flight_details_flight_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='jet_detail',
            name='jet_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
