# Generated by Django 3.2.3 on 2021-06-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_jet_detail_jet_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_details',
            name='adult',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='flight_details',
            name='childrens',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='flight_details',
            name='class_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
