# Generated by Django 3.2.3 on 2021-06-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20210602_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_details',
            name='departure_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
