# Generated by Django 3.2.3 on 2021-06-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_alter_flight_details_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_details',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
