# Generated by Django 3.2.3 on 2021-06-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_flight_details_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_details',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
    ]
