# Generated by Django 3.2.3 on 2021-06-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_flight_details_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_details',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight_details',
            name='arrival_time',
            field=models.TimeField(),
        ),
    ]
